### ISSUE TITLE
[Docs] Command Launcher usage

### ISSUE THREAD

**Issue by AlexNabokikh** [Skxxtz/sherlock#75]
I apologize for creating issues again and again, but I bumped into a problem and couldn't find a solution in the code or docs.

I am trying to add custom command into Sherlock using fallback's `command`:

```
  {
    "name": "Custom Scripts",
    "alias": "cs",
    "type": "command",
    "args": {
      "commands": {
        "Quit All Applications": {
          "icon": "quit",
          "exec": "hyprctl -j clients 2>/dev/null | jq -j '.[] | \"dispatch closewindow address:\\(.address); \"' | xargs -r hyprctl --batch 2>/dev/null",
          "search_string": "quit"
        }
      }
    },
    "priority": 4,
    "home": false,
    "shortcut": false
  },

```

I want to execute this simple one-liner from the Sherlock, but couldn't find the proper syntax to make it work.
Can someone clarify what would be the correct syntax?

**Comment by Skxxtz** [comment]
Hi, no worries, that's what issues are for. I assume you've already tried using the command in the terminal without using Sherlock? Have you also tried running Sherlock from the terminal and then executing the custom command?

**Comment by AlexNabokikh** [comment]
Yes, I've been using this command for years now, but I double-checked it and ran it in the terminal as well. I also tried to wrap it into a bash scrip and then provide a path as `exec` value. Used `bash -c` lines, provide full path to the script instead of using strip marker `~`, all kind of possible solutions, but nothing worked for me. It works for super simple commands like open browser, for instance. For more complex like this — no luck.

**Comment by Skxxtz** [comment]
Alright, seems like the problem were pipes. I've now fixed it as far as I can see. You can try it out on the unstable branch.

**Comment by Skxxtz** [comment]
Whenever you had a chance to test this, let me know if it worked, so we can close this issue.

**Comment by AlexNabokikh** [comment]
Hey @Skxxtz sorry for the delayed response. Unfortunately, I won't be able to check it in the next few weeks, so feel free to close the issue if you feel that it is completed.

**Comment by Skxxtz** [comment]
Alright, no worries. When you test it and it doesn't work, we can just reopen this issue then

**Comment by AlexNabokikh** [comment]
I've just installed `v0.1.12` which supposed to have a fix for this problem, but it still doesn't work.

**Comment by Skxxtz** [comment]
Oh that sucks. Could you launch Sherlock from the terminal and give me the output of your failed command execution? It should print something like `Failed to execute command "command | goes | here"` maybe we will see whats wrong with it.

**Comment by AlexNabokikh** [comment]
sherlock doesn't produce anything

https://github.com/user-attachments/assets/19dad0e5-bee6-4706-a45e-54ab7621b25a

**Comment by Skxxtz** [comment]
Alright, I've tried something on the new unstable branch. Could be working now.

**Comment by Skxxtz** [comment]
When I try your command on my machine, I get this: 
```sh
hyprctl -j clients 2>/dev/null | jq -j '.[] | dispatch closewindow address:\(.address); ' | xargs -r hyprctl --batch 2>/dev/null
jq: error: syntax error, unexpected IDENT, expecting end of file (Unix shell quoting issues?) at <top-level>, line 1:
.[] | dispatch closewindow address:\(.address);                
jq: 1 compile error
```

**Comment by Skxxtz** [comment]
Ok so I found the issue. Currently, Sherlock is replaceing all `"` with `'`. I think i have a fix in mind

**Comment by Skxxtz** [comment]
It's fixed now 🎉
